name: Python CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    uses: osfanbuff63/action-workflows/.github/workflows/python-matrix-pipenv.yml@v1
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
