name: Sync repo to Codeberg
on: [push]
jobs:
  codeberg-sync:
    uses: osfanbuff63/action-workflows/.github/workflows/git-repo-sync.yml
    with:
      target_url: https://codeberg.org/osfanbuff63/rss-news
    secrets:
      target_token: ${{ secrets.CODEBERG_TOKEN }}